version: '3.5' 

services: 
    simple-web-service2: 
      image: devopsdockeruh/simple-web-service 
      build: . 
      volumes: 
        - ./text.log:/usr/src/app/text.log
      ports:
        - 8080:8080
      command: server
      container_name: simple-web-service2
