version: '3.5' 

services: 
    backend: 
      build: ./backend
      environment:
        - REDIS_HOST=redis
      ports:
        - 8080:8080
      container_name: backend

    frontend: 
      build: ./frontend 
      ports:
        - 5000:5000
      container_name: frontend

    redis: 
      image: redis
      ports:
        - 6379:6379
      container_name: redis
