version: '3.5' 

services: 
    backend: 
      build: ./backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
      ports:
        - 8080:8080
      container_name: backend

    frontend: 
      build: ./frontend 
      ports:
        - 5000:5000
      container_name: frontend

    redis: 
      image: redis
      ports:
        - 6379:6379
      container_name: redis
      
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
      container_name: postgres
      volumes:
        - database:/var/lib/postgresql/data
    
    nginx:
      image: nginx:stable-alpine
      ports:
        - 80:80
        - 443:443
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  database:
